---
- name: Update Debian Repository
  hosts: servers
  become: no
  gather_facts: False
  remote_user: rusdi
  tasks:
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes
  
  - name: Install required packages
    apt:
      name:
        - build-essential
        - curl
        - libssl-dev
        - wget
      state: latest
      
